# Generated by Django 4.0.2 on 2022-03-02 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=127, unique=True, verbose_name='Электронная почта')),
                ('username', models.CharField(max_length=127, unique=True, verbose_name='Имя пользователя')),
                ('ip_address', models.CharField(blank=True, default='', help_text='Для ограничения доступа пользователя на сайт', max_length=255, verbose_name='IP-адрес')),
                ('status', models.CharField(choices=[('ONLINE', 'Онлайн'), ('OFFLINE', 'Оффлайн'), ('DELETE', 'Удалён'), ('BLOCKED', 'Заблокирован')], default='OFFLINE', max_length=16, verbose_name='Статус')),
                ('discount', models.IntegerField(default='0')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', help_text='Содержит краткое описание товаров, которые можно найти в данной рубрике.', verbose_name='Описание')),
                ('availability', models.BooleanField(blank=True, default=False, help_text='Доступность категории при просмотре. в случае отсутствия - в категории нет товаров', verbose_name='Доступность')),
                ('quantity_of_goods', models.IntegerField(blank=True, default=0, editable=False, verbose_name='Количество товаров')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, default='', help_text='Содержит краткое описание производителя: историю фирмы, сертификаты качества, различные награды и участие в выставках, повышающие доверие покупателей.', verbose_name='Описание')),
                ('quantity_of_goods', models.IntegerField(blank=True, default=0, editable=False, verbose_name='Количество товаров')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.JSONField(blank=True, help_text='Описание продукта в формате JSON {"blocks":[{"header":"","description":""}]}', null=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, default='0', verbose_name='Цена')),
                ('availability', models.BooleanField(blank=True, default=True, verbose_name='Доступность')),
                ('option', models.JSONField(blank=True, help_text='Список различных характеристик в формате JSON {"blocks":["blockname":"",{"options":[{"name":"","value":""}]}]}', null=True, verbose_name='Опции')),
                ('quantity_of_goods', models.IntegerField(blank=True, default=0, editable=False, verbose_name='Количество товаров')),
                ('product_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categories', verbose_name='Категория')),
                ('product_manufacturers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manufacturers', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', help_text='Содержит краткое описание товаров, которые можно найти в данной рубрике.', verbose_name='Описание')),
                ('path', models.CharField(help_text='Путь отностительно главной страницы по которому будет представлен данный объект', max_length=256, unique=True, verbose_name='Путь')),
                ('products', models.ManyToManyField(to='api.Products')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.IntegerField(default='0')),
                ('quantity_of_goods', models.IntegerField(default=0, verbose_name='Количество товаров')),
                ('delivery_method', models.CharField(choices=[('DELIVERY', 'Доставка'), ('PICKUP', 'Самовывоз')], default='OFFLINE', max_length=16, verbose_name='Способ доставки')),
                ('payment_method', models.CharField(choices=[('CASH', 'Наличные'), ('BANKCARD', 'Банковская карта')], default='CASH', max_length=16, verbose_name='Способ доставки')),
                ('status', models.CharField(choices=[('INPROCESSING', 'В обработке'), ('COMPLETED', 'Выполнен'), ('REJECTED', 'Отклонен')], default='INPROCESSING', max_length=16, verbose_name='Способ доставки')),
                ('commentary', models.TextField(blank=True, default='')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ManyToManyField(blank=True, to='api.Products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['customers'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
