# Generated by Django 4.0.2 on 2022-03-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_orders_product_productsorders_orders_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductsOrders',
        ),
        migrations.AddField(
            model_name='basket',
            name='orders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orders', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='basket',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Basket',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='api.basket', verbose_name='Корзина'),
            preserve_default=False,
        ),
    ]
