# Generated by Django 4.0.2 on 2022-03-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_basket_orders_id_alter_basket_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='orders_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_price',
            field=models.IntegerField(default='0', verbose_name='Цена заказа'),
        ),
    ]
